(executable
 (name subsocia_eliom_module)
 (modes js byte)
 (preprocess (pps js_of_ocaml-ppx))
 (js_of_ocaml
  (build_runtime_flags :standard --enable use-js-string)
  (flags :standard --enable with-js-error --enable use-js-string))
 (libraries
    js_of_ocaml
    js_of_ocaml-lwt
    eliom.client
    lwt
    panograph
    panograph.client
    prime
    prime.unstable
    react
    subsocia))

(dynamic_include ../dune.client)

(install
 (package subsocia-eliom)
 (section share)
 (files (subsocia_eliom_module.bc.js as static/subsocia_eliom_module.js)))
